name = "NMRSimulations"
uuid = "b68b6c62-c5d0-40db-9816-3dc03735083d"
authors = ["Ashish Panigrahi <ashish.panigrahi@protonmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
